-- 0003_drop_destructive_rebuild_note.sql
-- P0-3 fix: 删 DO destructive schema rebuild
--
-- 背景 (2026-06-08 之前):
--   packages/do-worker/src/ticker-hub.js 里 SCHEMA_REBUILD const + applyMigrations
--   的 DROP 循环, 在 DO 每次冷启动时 DROP portfolio_state / signals / trades /
--   alert_cooldowns 四张表, 然后用 SQL_SCHEMA 重建. 历史 trades / signals 全部
--   清零 — 每次 deploy / DO restart 都会让用户失去所有决策日志和成交记录.
--
-- 修复 (P0-3):
--   - 删除 SCHEMA_REBUILD const 整段
--   - applyMigrations 改为纯 idempotent (只跑 SQL_SCHEMA 里的 CREATE TABLE IF NOT EXISTS)
--   - DO 启动不再清任何表, 历史 trades / signals / portfolio_state 全部保留
--   - 加 _migrations 跟踪表 (id / name / applied_at), schema 演进可追溯
--
-- 此 migration 文件为 documentation-only:
--   - 不含 DDL (新增的 _migrations 表已在 SQL_SCHEMA 内 CREATE TABLE IF NOT EXISTS,
--     老 DO 重启时自动建表)
--   - 留作历史里程碑, 标识 "从此 PR 起, schema 变更不再 destructive"
--   - 后续 PR5 加 dca_rounds 表时, 会新增 0004_add_dca_rounds.sql 走同一条
--     idempotent 路径
--
-- 验证方式:
--   - 启动 DO 一次, 写几条 trades / signals
--   - 触发 DO restart (deploy / evicit)
--   - 重新读 trades / signals: 数据仍在
--   - 查 _migrations 表: 暂时无条目 (此 migration 文件无 DDL, 不写 _migrations)
--     — 真正的 migration tracking 在后续 PR 的实际 DDL 文件里启用
